### ISSUE TITLE
28th July Peer-to-peer CR

### ISSUE THREAD

**Issue by Zilola-Nazarova** [Ochiengsteven/leader-board#4]
Highlights 🥇 

- beautiful design;
- all functionalities work;
- input validations applied;
- the project has Demo link;

### Improvement suggestions ♻️ 

- [ ] At the bottom of the page there's a white line. Please adjust your CSS to remove this line;

**Comment by Ochiengsteven** [comment]
Thank you all for reviewing the code and providing your valuable feedback on this GitHub issue. Your insights are greatly appreciated in helping me make improvements. Let's keep collaborating and building better software together!
![giphy](https://github.com/Ochiengsteven/leader-board/assets/91716656/866a4a97-64d7-4621-9983-d92f6a618a91)
